// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bloodp.proto

package grpc.jake.bloodp;

public interface BloodpAnswerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcheart.BloodpAnswer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string helplink1 = 3;</code>
   */
  java.lang.String getHelplink1();
  /**
   * <code>string helplink1 = 3;</code>
   */
  com.google.protobuf.ByteString
      getHelplink1Bytes();

  /**
   * <code>string helplink2 = 4;</code>
   */
  java.lang.String getHelplink2();
  /**
   * <code>string helplink2 = 4;</code>
   */
  com.google.protobuf.ByteString
      getHelplink2Bytes();
}
