// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bloodp.proto

package grpc.jake.bloodp;

public interface BloodpRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcheart.BloodpRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 systolic = 1;</code>
   */
  int getSystolic();

  /**
   * <code>int32 diastolic = 2;</code>
   */
  int getDiastolic();
}
