// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bloodp.proto

package grpc.jake.bloodp;

/**
 * Protobuf type {@code grpcheart.BloodpReply}
 */
public  final class BloodpReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpcheart.BloodpReply)
    BloodpReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BloodpReply.newBuilder() to construct.
  private BloodpReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BloodpReply() {
    bp_ = "";
    bpmessage_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BloodpReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            bp_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            bpmessage_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.jake.bloodp.BloodpServiceImpl.internal_static_grpcheart_BloodpReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.jake.bloodp.BloodpServiceImpl.internal_static_grpcheart_BloodpReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.jake.bloodp.BloodpReply.class, grpc.jake.bloodp.BloodpReply.Builder.class);
  }

  public static final int BP_FIELD_NUMBER = 1;
  private volatile java.lang.Object bp_;
  /**
   * <code>string bp = 1;</code>
   */
  public java.lang.String getBp() {
    java.lang.Object ref = bp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bp_ = s;
      return s;
    }
  }
  /**
   * <code>string bp = 1;</code>
   */
  public com.google.protobuf.ByteString
      getBpBytes() {
    java.lang.Object ref = bp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BPMESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object bpmessage_;
  /**
   * <code>string bpmessage = 2;</code>
   */
  public java.lang.String getBpmessage() {
    java.lang.Object ref = bpmessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bpmessage_ = s;
      return s;
    }
  }
  /**
   * <code>string bpmessage = 2;</code>
   */
  public com.google.protobuf.ByteString
      getBpmessageBytes() {
    java.lang.Object ref = bpmessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bpmessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getBpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, bp_);
    }
    if (!getBpmessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bpmessage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, bp_);
    }
    if (!getBpmessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bpmessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.jake.bloodp.BloodpReply)) {
      return super.equals(obj);
    }
    grpc.jake.bloodp.BloodpReply other = (grpc.jake.bloodp.BloodpReply) obj;

    boolean result = true;
    result = result && getBp()
        .equals(other.getBp());
    result = result && getBpmessage()
        .equals(other.getBpmessage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BP_FIELD_NUMBER;
    hash = (53 * hash) + getBp().hashCode();
    hash = (37 * hash) + BPMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getBpmessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.jake.bloodp.BloodpReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.jake.bloodp.BloodpReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.jake.bloodp.BloodpReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.jake.bloodp.BloodpReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.jake.bloodp.BloodpReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.jake.bloodp.BloodpReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.jake.bloodp.BloodpReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.jake.bloodp.BloodpReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.jake.bloodp.BloodpReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.jake.bloodp.BloodpReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.jake.bloodp.BloodpReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.jake.bloodp.BloodpReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.jake.bloodp.BloodpReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpcheart.BloodpReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpcheart.BloodpReply)
      grpc.jake.bloodp.BloodpReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.jake.bloodp.BloodpServiceImpl.internal_static_grpcheart_BloodpReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.jake.bloodp.BloodpServiceImpl.internal_static_grpcheart_BloodpReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.jake.bloodp.BloodpReply.class, grpc.jake.bloodp.BloodpReply.Builder.class);
    }

    // Construct using grpc.jake.bloodp.BloodpReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bp_ = "";

      bpmessage_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.jake.bloodp.BloodpServiceImpl.internal_static_grpcheart_BloodpReply_descriptor;
    }

    @java.lang.Override
    public grpc.jake.bloodp.BloodpReply getDefaultInstanceForType() {
      return grpc.jake.bloodp.BloodpReply.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.jake.bloodp.BloodpReply build() {
      grpc.jake.bloodp.BloodpReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.jake.bloodp.BloodpReply buildPartial() {
      grpc.jake.bloodp.BloodpReply result = new grpc.jake.bloodp.BloodpReply(this);
      result.bp_ = bp_;
      result.bpmessage_ = bpmessage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.jake.bloodp.BloodpReply) {
        return mergeFrom((grpc.jake.bloodp.BloodpReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.jake.bloodp.BloodpReply other) {
      if (other == grpc.jake.bloodp.BloodpReply.getDefaultInstance()) return this;
      if (!other.getBp().isEmpty()) {
        bp_ = other.bp_;
        onChanged();
      }
      if (!other.getBpmessage().isEmpty()) {
        bpmessage_ = other.bpmessage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.jake.bloodp.BloodpReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.jake.bloodp.BloodpReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object bp_ = "";
    /**
     * <code>string bp = 1;</code>
     */
    public java.lang.String getBp() {
      java.lang.Object ref = bp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bp = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBpBytes() {
      java.lang.Object ref = bp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bp = 1;</code>
     */
    public Builder setBp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string bp = 1;</code>
     */
    public Builder clearBp() {
      
      bp_ = getDefaultInstance().getBp();
      onChanged();
      return this;
    }
    /**
     * <code>string bp = 1;</code>
     */
    public Builder setBpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bp_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object bpmessage_ = "";
    /**
     * <code>string bpmessage = 2;</code>
     */
    public java.lang.String getBpmessage() {
      java.lang.Object ref = bpmessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bpmessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bpmessage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBpmessageBytes() {
      java.lang.Object ref = bpmessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bpmessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bpmessage = 2;</code>
     */
    public Builder setBpmessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bpmessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string bpmessage = 2;</code>
     */
    public Builder clearBpmessage() {
      
      bpmessage_ = getDefaultInstance().getBpmessage();
      onChanged();
      return this;
    }
    /**
     * <code>string bpmessage = 2;</code>
     */
    public Builder setBpmessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bpmessage_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpcheart.BloodpReply)
  }

  // @@protoc_insertion_point(class_scope:grpcheart.BloodpReply)
  private static final grpc.jake.bloodp.BloodpReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.jake.bloodp.BloodpReply();
  }

  public static grpc.jake.bloodp.BloodpReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BloodpReply>
      PARSER = new com.google.protobuf.AbstractParser<BloodpReply>() {
    @java.lang.Override
    public BloodpReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BloodpReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BloodpReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BloodpReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.jake.bloodp.BloodpReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

