// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bloodp.proto

package grpc.jake.bloodp;

public interface BloodpReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcheart.BloodpReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bp = 1;</code>
   */
  java.lang.String getBp();
  /**
   * <code>string bp = 1;</code>
   */
  com.google.protobuf.ByteString
      getBpBytes();

  /**
   * <code>string bpmessage = 2;</code>
   */
  java.lang.String getBpmessage();
  /**
   * <code>string bpmessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getBpmessageBytes();
}
