// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bloodp.proto

package grpc.jake.bloodp;

/**
 * Protobuf type {@code grpcheart.BloodpAnswer}
 */
public  final class BloodpAnswer extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpcheart.BloodpAnswer)
    BloodpAnswerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BloodpAnswer.newBuilder() to construct.
  private BloodpAnswer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BloodpAnswer() {
    helplink1_ = "";
    helplink2_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BloodpAnswer(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            helplink1_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            helplink2_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.jake.bloodp.BloodpServiceImpl.internal_static_grpcheart_BloodpAnswer_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.jake.bloodp.BloodpServiceImpl.internal_static_grpcheart_BloodpAnswer_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.jake.bloodp.BloodpAnswer.class, grpc.jake.bloodp.BloodpAnswer.Builder.class);
  }

  public static final int HELPLINK1_FIELD_NUMBER = 3;
  private volatile java.lang.Object helplink1_;
  /**
   * <code>string helplink1 = 3;</code>
   */
  public java.lang.String getHelplink1() {
    java.lang.Object ref = helplink1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      helplink1_ = s;
      return s;
    }
  }
  /**
   * <code>string helplink1 = 3;</code>
   */
  public com.google.protobuf.ByteString
      getHelplink1Bytes() {
    java.lang.Object ref = helplink1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      helplink1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HELPLINK2_FIELD_NUMBER = 4;
  private volatile java.lang.Object helplink2_;
  /**
   * <code>string helplink2 = 4;</code>
   */
  public java.lang.String getHelplink2() {
    java.lang.Object ref = helplink2_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      helplink2_ = s;
      return s;
    }
  }
  /**
   * <code>string helplink2 = 4;</code>
   */
  public com.google.protobuf.ByteString
      getHelplink2Bytes() {
    java.lang.Object ref = helplink2_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      helplink2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getHelplink1Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, helplink1_);
    }
    if (!getHelplink2Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, helplink2_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getHelplink1Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, helplink1_);
    }
    if (!getHelplink2Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, helplink2_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.jake.bloodp.BloodpAnswer)) {
      return super.equals(obj);
    }
    grpc.jake.bloodp.BloodpAnswer other = (grpc.jake.bloodp.BloodpAnswer) obj;

    boolean result = true;
    result = result && getHelplink1()
        .equals(other.getHelplink1());
    result = result && getHelplink2()
        .equals(other.getHelplink2());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HELPLINK1_FIELD_NUMBER;
    hash = (53 * hash) + getHelplink1().hashCode();
    hash = (37 * hash) + HELPLINK2_FIELD_NUMBER;
    hash = (53 * hash) + getHelplink2().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.jake.bloodp.BloodpAnswer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.jake.bloodp.BloodpAnswer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.jake.bloodp.BloodpAnswer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.jake.bloodp.BloodpAnswer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.jake.bloodp.BloodpAnswer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.jake.bloodp.BloodpAnswer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.jake.bloodp.BloodpAnswer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.jake.bloodp.BloodpAnswer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.jake.bloodp.BloodpAnswer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.jake.bloodp.BloodpAnswer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.jake.bloodp.BloodpAnswer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.jake.bloodp.BloodpAnswer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.jake.bloodp.BloodpAnswer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpcheart.BloodpAnswer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpcheart.BloodpAnswer)
      grpc.jake.bloodp.BloodpAnswerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.jake.bloodp.BloodpServiceImpl.internal_static_grpcheart_BloodpAnswer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.jake.bloodp.BloodpServiceImpl.internal_static_grpcheart_BloodpAnswer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.jake.bloodp.BloodpAnswer.class, grpc.jake.bloodp.BloodpAnswer.Builder.class);
    }

    // Construct using grpc.jake.bloodp.BloodpAnswer.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      helplink1_ = "";

      helplink2_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.jake.bloodp.BloodpServiceImpl.internal_static_grpcheart_BloodpAnswer_descriptor;
    }

    @java.lang.Override
    public grpc.jake.bloodp.BloodpAnswer getDefaultInstanceForType() {
      return grpc.jake.bloodp.BloodpAnswer.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.jake.bloodp.BloodpAnswer build() {
      grpc.jake.bloodp.BloodpAnswer result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.jake.bloodp.BloodpAnswer buildPartial() {
      grpc.jake.bloodp.BloodpAnswer result = new grpc.jake.bloodp.BloodpAnswer(this);
      result.helplink1_ = helplink1_;
      result.helplink2_ = helplink2_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.jake.bloodp.BloodpAnswer) {
        return mergeFrom((grpc.jake.bloodp.BloodpAnswer)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.jake.bloodp.BloodpAnswer other) {
      if (other == grpc.jake.bloodp.BloodpAnswer.getDefaultInstance()) return this;
      if (!other.getHelplink1().isEmpty()) {
        helplink1_ = other.helplink1_;
        onChanged();
      }
      if (!other.getHelplink2().isEmpty()) {
        helplink2_ = other.helplink2_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.jake.bloodp.BloodpAnswer parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.jake.bloodp.BloodpAnswer) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object helplink1_ = "";
    /**
     * <code>string helplink1 = 3;</code>
     */
    public java.lang.String getHelplink1() {
      java.lang.Object ref = helplink1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        helplink1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string helplink1 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHelplink1Bytes() {
      java.lang.Object ref = helplink1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        helplink1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string helplink1 = 3;</code>
     */
    public Builder setHelplink1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      helplink1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string helplink1 = 3;</code>
     */
    public Builder clearHelplink1() {
      
      helplink1_ = getDefaultInstance().getHelplink1();
      onChanged();
      return this;
    }
    /**
     * <code>string helplink1 = 3;</code>
     */
    public Builder setHelplink1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      helplink1_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object helplink2_ = "";
    /**
     * <code>string helplink2 = 4;</code>
     */
    public java.lang.String getHelplink2() {
      java.lang.Object ref = helplink2_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        helplink2_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string helplink2 = 4;</code>
     */
    public com.google.protobuf.ByteString
        getHelplink2Bytes() {
      java.lang.Object ref = helplink2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        helplink2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string helplink2 = 4;</code>
     */
    public Builder setHelplink2(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      helplink2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string helplink2 = 4;</code>
     */
    public Builder clearHelplink2() {
      
      helplink2_ = getDefaultInstance().getHelplink2();
      onChanged();
      return this;
    }
    /**
     * <code>string helplink2 = 4;</code>
     */
    public Builder setHelplink2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      helplink2_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpcheart.BloodpAnswer)
  }

  // @@protoc_insertion_point(class_scope:grpcheart.BloodpAnswer)
  private static final grpc.jake.bloodp.BloodpAnswer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.jake.bloodp.BloodpAnswer();
  }

  public static grpc.jake.bloodp.BloodpAnswer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BloodpAnswer>
      PARSER = new com.google.protobuf.AbstractParser<BloodpAnswer>() {
    @java.lang.Override
    public BloodpAnswer parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BloodpAnswer(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BloodpAnswer> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BloodpAnswer> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.jake.bloodp.BloodpAnswer getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

