// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bloodp.proto

package grpc.jake.bloodp;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcheart.Empty)
    com.google.protobuf.MessageOrBuilder {
}
