// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cholesterol.proto

package grpc.jake.cholesterol;

public interface CholesterolRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcheart.CholesterolRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 total = 1;</code>
   */
  int getTotal();

  /**
   * <code>int32 ldl = 2;</code>
   */
  int getLdl();

  /**
   * <code>int32 hdl = 3;</code>
   */
  int getHdl();

  /**
   * <code>int32 Triglycerides = 4;</code>
   */
  int getTriglycerides();
}
