// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cholesterol.proto

package grpc.jake.cholesterol;

public interface CholesterolReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcheart.CholesterolReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string total = 1;</code>
   */
  java.lang.String getTotal();
  /**
   * <code>string total = 1;</code>
   */
  com.google.protobuf.ByteString
      getTotalBytes();

  /**
   * <code>string ansldl = 2;</code>
   */
  java.lang.String getAnsldl();
  /**
   * <code>string ansldl = 2;</code>
   */
  com.google.protobuf.ByteString
      getAnsldlBytes();

  /**
   * <code>string anshdl = 3;</code>
   */
  java.lang.String getAnshdl();
  /**
   * <code>string anshdl = 3;</code>
   */
  com.google.protobuf.ByteString
      getAnshdlBytes();

  /**
   * <code>string anstri = 4;</code>
   */
  java.lang.String getAnstri();
  /**
   * <code>string anstri = 4;</code>
   */
  com.google.protobuf.ByteString
      getAnstriBytes();
}
