// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cholesterol.proto

package grpc.jake.cholesterol;

public final class CholesterolServiceImpl {
  private CholesterolServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcheart_CholesterolRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcheart_CholesterolRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcheart_CholesterolReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcheart_CholesterolReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcheart_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcheart_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcheart_CholesterolAnswer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcheart_CholesterolAnswer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021cholesterol.proto\022\tgrpcheart\"T\n\022Choles" +
      "terolRequest\022\r\n\005total\030\001 \001(\005\022\013\n\003ldl\030\002 \001(\005" +
      "\022\013\n\003hdl\030\003 \001(\005\022\025\n\rTriglycerides\030\004 \001(\005\"Q\n\020" +
      "CholesterolReply\022\r\n\005total\030\001 \001(\t\022\016\n\006ansld" +
      "l\030\002 \001(\t\022\016\n\006anshdl\030\003 \001(\t\022\016\n\006anstri\030\004 \001(\t\"" +
      "\007\n\005Empty\"9\n\021CholesterolAnswer\022\021\n\thelplin" +
      "k1\030\001 \001(\t\022\021\n\thelplink2\030\002 \001(\t2\250\001\n\013Choleste" +
      "rol\022T\n\026CholesterolCalculation\022\035.grpchear" +
      "t.CholesterolRequest\032\033.grpcheart.Cholest" +
      "erolReply\022C\n\021CholesterolAdvice\022\020.grpchea" +
      "rt.Empty\032\034.grpcheart.CholesterolAnswerB1" +
      "\n\025grpc.jake.cholesterolB\026CholesterolServ" +
      "iceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_grpcheart_CholesterolRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpcheart_CholesterolRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcheart_CholesterolRequest_descriptor,
        new java.lang.String[] { "Total", "Ldl", "Hdl", "Triglycerides", });
    internal_static_grpcheart_CholesterolReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpcheart_CholesterolReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcheart_CholesterolReply_descriptor,
        new java.lang.String[] { "Total", "Ansldl", "Anshdl", "Anstri", });
    internal_static_grpcheart_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpcheart_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcheart_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_grpcheart_CholesterolAnswer_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_grpcheart_CholesterolAnswer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcheart_CholesterolAnswer_descriptor,
        new java.lang.String[] { "Helplink1", "Helplink2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
