// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cholesterol.proto

package grpc.jake.cholesterol;

/**
 * Protobuf type {@code grpcheart.CholesterolReply}
 */
public  final class CholesterolReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpcheart.CholesterolReply)
    CholesterolReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CholesterolReply.newBuilder() to construct.
  private CholesterolReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CholesterolReply() {
    total_ = "";
    ansldl_ = "";
    anshdl_ = "";
    anstri_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CholesterolReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            total_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            ansldl_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            anshdl_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            anstri_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.jake.cholesterol.CholesterolServiceImpl.internal_static_grpcheart_CholesterolReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.jake.cholesterol.CholesterolServiceImpl.internal_static_grpcheart_CholesterolReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.jake.cholesterol.CholesterolReply.class, grpc.jake.cholesterol.CholesterolReply.Builder.class);
  }

  public static final int TOTAL_FIELD_NUMBER = 1;
  private volatile java.lang.Object total_;
  /**
   * <code>string total = 1;</code>
   */
  public java.lang.String getTotal() {
    java.lang.Object ref = total_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      total_ = s;
      return s;
    }
  }
  /**
   * <code>string total = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTotalBytes() {
    java.lang.Object ref = total_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      total_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ANSLDL_FIELD_NUMBER = 2;
  private volatile java.lang.Object ansldl_;
  /**
   * <code>string ansldl = 2;</code>
   */
  public java.lang.String getAnsldl() {
    java.lang.Object ref = ansldl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ansldl_ = s;
      return s;
    }
  }
  /**
   * <code>string ansldl = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAnsldlBytes() {
    java.lang.Object ref = ansldl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ansldl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ANSHDL_FIELD_NUMBER = 3;
  private volatile java.lang.Object anshdl_;
  /**
   * <code>string anshdl = 3;</code>
   */
  public java.lang.String getAnshdl() {
    java.lang.Object ref = anshdl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      anshdl_ = s;
      return s;
    }
  }
  /**
   * <code>string anshdl = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAnshdlBytes() {
    java.lang.Object ref = anshdl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      anshdl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ANSTRI_FIELD_NUMBER = 4;
  private volatile java.lang.Object anstri_;
  /**
   * <code>string anstri = 4;</code>
   */
  public java.lang.String getAnstri() {
    java.lang.Object ref = anstri_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      anstri_ = s;
      return s;
    }
  }
  /**
   * <code>string anstri = 4;</code>
   */
  public com.google.protobuf.ByteString
      getAnstriBytes() {
    java.lang.Object ref = anstri_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      anstri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTotalBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, total_);
    }
    if (!getAnsldlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ansldl_);
    }
    if (!getAnshdlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, anshdl_);
    }
    if (!getAnstriBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, anstri_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTotalBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, total_);
    }
    if (!getAnsldlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ansldl_);
    }
    if (!getAnshdlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, anshdl_);
    }
    if (!getAnstriBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, anstri_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.jake.cholesterol.CholesterolReply)) {
      return super.equals(obj);
    }
    grpc.jake.cholesterol.CholesterolReply other = (grpc.jake.cholesterol.CholesterolReply) obj;

    boolean result = true;
    result = result && getTotal()
        .equals(other.getTotal());
    result = result && getAnsldl()
        .equals(other.getAnsldl());
    result = result && getAnshdl()
        .equals(other.getAnshdl());
    result = result && getAnstri()
        .equals(other.getAnstri());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + getTotal().hashCode();
    hash = (37 * hash) + ANSLDL_FIELD_NUMBER;
    hash = (53 * hash) + getAnsldl().hashCode();
    hash = (37 * hash) + ANSHDL_FIELD_NUMBER;
    hash = (53 * hash) + getAnshdl().hashCode();
    hash = (37 * hash) + ANSTRI_FIELD_NUMBER;
    hash = (53 * hash) + getAnstri().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.jake.cholesterol.CholesterolReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.jake.cholesterol.CholesterolReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.jake.cholesterol.CholesterolReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.jake.cholesterol.CholesterolReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.jake.cholesterol.CholesterolReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.jake.cholesterol.CholesterolReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.jake.cholesterol.CholesterolReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.jake.cholesterol.CholesterolReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.jake.cholesterol.CholesterolReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.jake.cholesterol.CholesterolReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.jake.cholesterol.CholesterolReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.jake.cholesterol.CholesterolReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.jake.cholesterol.CholesterolReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpcheart.CholesterolReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpcheart.CholesterolReply)
      grpc.jake.cholesterol.CholesterolReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.jake.cholesterol.CholesterolServiceImpl.internal_static_grpcheart_CholesterolReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.jake.cholesterol.CholesterolServiceImpl.internal_static_grpcheart_CholesterolReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.jake.cholesterol.CholesterolReply.class, grpc.jake.cholesterol.CholesterolReply.Builder.class);
    }

    // Construct using grpc.jake.cholesterol.CholesterolReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      total_ = "";

      ansldl_ = "";

      anshdl_ = "";

      anstri_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.jake.cholesterol.CholesterolServiceImpl.internal_static_grpcheart_CholesterolReply_descriptor;
    }

    @java.lang.Override
    public grpc.jake.cholesterol.CholesterolReply getDefaultInstanceForType() {
      return grpc.jake.cholesterol.CholesterolReply.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.jake.cholesterol.CholesterolReply build() {
      grpc.jake.cholesterol.CholesterolReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.jake.cholesterol.CholesterolReply buildPartial() {
      grpc.jake.cholesterol.CholesterolReply result = new grpc.jake.cholesterol.CholesterolReply(this);
      result.total_ = total_;
      result.ansldl_ = ansldl_;
      result.anshdl_ = anshdl_;
      result.anstri_ = anstri_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.jake.cholesterol.CholesterolReply) {
        return mergeFrom((grpc.jake.cholesterol.CholesterolReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.jake.cholesterol.CholesterolReply other) {
      if (other == grpc.jake.cholesterol.CholesterolReply.getDefaultInstance()) return this;
      if (!other.getTotal().isEmpty()) {
        total_ = other.total_;
        onChanged();
      }
      if (!other.getAnsldl().isEmpty()) {
        ansldl_ = other.ansldl_;
        onChanged();
      }
      if (!other.getAnshdl().isEmpty()) {
        anshdl_ = other.anshdl_;
        onChanged();
      }
      if (!other.getAnstri().isEmpty()) {
        anstri_ = other.anstri_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.jake.cholesterol.CholesterolReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.jake.cholesterol.CholesterolReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object total_ = "";
    /**
     * <code>string total = 1;</code>
     */
    public java.lang.String getTotal() {
      java.lang.Object ref = total_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        total_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string total = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTotalBytes() {
      java.lang.Object ref = total_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        total_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string total = 1;</code>
     */
    public Builder setTotal(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      total_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string total = 1;</code>
     */
    public Builder clearTotal() {
      
      total_ = getDefaultInstance().getTotal();
      onChanged();
      return this;
    }
    /**
     * <code>string total = 1;</code>
     */
    public Builder setTotalBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      total_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ansldl_ = "";
    /**
     * <code>string ansldl = 2;</code>
     */
    public java.lang.String getAnsldl() {
      java.lang.Object ref = ansldl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ansldl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ansldl = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAnsldlBytes() {
      java.lang.Object ref = ansldl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ansldl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ansldl = 2;</code>
     */
    public Builder setAnsldl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ansldl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ansldl = 2;</code>
     */
    public Builder clearAnsldl() {
      
      ansldl_ = getDefaultInstance().getAnsldl();
      onChanged();
      return this;
    }
    /**
     * <code>string ansldl = 2;</code>
     */
    public Builder setAnsldlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ansldl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object anshdl_ = "";
    /**
     * <code>string anshdl = 3;</code>
     */
    public java.lang.String getAnshdl() {
      java.lang.Object ref = anshdl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        anshdl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string anshdl = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAnshdlBytes() {
      java.lang.Object ref = anshdl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        anshdl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string anshdl = 3;</code>
     */
    public Builder setAnshdl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      anshdl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string anshdl = 3;</code>
     */
    public Builder clearAnshdl() {
      
      anshdl_ = getDefaultInstance().getAnshdl();
      onChanged();
      return this;
    }
    /**
     * <code>string anshdl = 3;</code>
     */
    public Builder setAnshdlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      anshdl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object anstri_ = "";
    /**
     * <code>string anstri = 4;</code>
     */
    public java.lang.String getAnstri() {
      java.lang.Object ref = anstri_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        anstri_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string anstri = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAnstriBytes() {
      java.lang.Object ref = anstri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        anstri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string anstri = 4;</code>
     */
    public Builder setAnstri(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      anstri_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string anstri = 4;</code>
     */
    public Builder clearAnstri() {
      
      anstri_ = getDefaultInstance().getAnstri();
      onChanged();
      return this;
    }
    /**
     * <code>string anstri = 4;</code>
     */
    public Builder setAnstriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      anstri_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpcheart.CholesterolReply)
  }

  // @@protoc_insertion_point(class_scope:grpcheart.CholesterolReply)
  private static final grpc.jake.cholesterol.CholesterolReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.jake.cholesterol.CholesterolReply();
  }

  public static grpc.jake.cholesterol.CholesterolReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CholesterolReply>
      PARSER = new com.google.protobuf.AbstractParser<CholesterolReply>() {
    @java.lang.Override
    public CholesterolReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CholesterolReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CholesterolReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CholesterolReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.jake.cholesterol.CholesterolReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

