// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cholesterol.proto

package grpc.jake.cholesterol;

public interface CholesterolAnswerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcheart.CholesterolAnswer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string helplink1 = 1;</code>
   */
  java.lang.String getHelplink1();
  /**
   * <code>string helplink1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getHelplink1Bytes();

  /**
   * <code>string helplink2 = 2;</code>
   */
  java.lang.String getHelplink2();
  /**
   * <code>string helplink2 = 2;</code>
   */
  com.google.protobuf.ByteString
      getHelplink2Bytes();
}
