// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cholesterol.proto

package grpc.jake.cholesterol;

/**
 * Protobuf type {@code grpcheart.CholesterolRequest}
 */
public  final class CholesterolRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpcheart.CholesterolRequest)
    CholesterolRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CholesterolRequest.newBuilder() to construct.
  private CholesterolRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CholesterolRequest() {
    total_ = 0;
    ldl_ = 0;
    hdl_ = 0;
    triglycerides_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CholesterolRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            total_ = input.readInt32();
            break;
          }
          case 16: {

            ldl_ = input.readInt32();
            break;
          }
          case 24: {

            hdl_ = input.readInt32();
            break;
          }
          case 32: {

            triglycerides_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.jake.cholesterol.CholesterolServiceImpl.internal_static_grpcheart_CholesterolRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.jake.cholesterol.CholesterolServiceImpl.internal_static_grpcheart_CholesterolRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.jake.cholesterol.CholesterolRequest.class, grpc.jake.cholesterol.CholesterolRequest.Builder.class);
  }

  public static final int TOTAL_FIELD_NUMBER = 1;
  private int total_;
  /**
   * <code>int32 total = 1;</code>
   */
  public int getTotal() {
    return total_;
  }

  public static final int LDL_FIELD_NUMBER = 2;
  private int ldl_;
  /**
   * <code>int32 ldl = 2;</code>
   */
  public int getLdl() {
    return ldl_;
  }

  public static final int HDL_FIELD_NUMBER = 3;
  private int hdl_;
  /**
   * <code>int32 hdl = 3;</code>
   */
  public int getHdl() {
    return hdl_;
  }

  public static final int TRIGLYCERIDES_FIELD_NUMBER = 4;
  private int triglycerides_;
  /**
   * <code>int32 Triglycerides = 4;</code>
   */
  public int getTriglycerides() {
    return triglycerides_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (total_ != 0) {
      output.writeInt32(1, total_);
    }
    if (ldl_ != 0) {
      output.writeInt32(2, ldl_);
    }
    if (hdl_ != 0) {
      output.writeInt32(3, hdl_);
    }
    if (triglycerides_ != 0) {
      output.writeInt32(4, triglycerides_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (total_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, total_);
    }
    if (ldl_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, ldl_);
    }
    if (hdl_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, hdl_);
    }
    if (triglycerides_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, triglycerides_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.jake.cholesterol.CholesterolRequest)) {
      return super.equals(obj);
    }
    grpc.jake.cholesterol.CholesterolRequest other = (grpc.jake.cholesterol.CholesterolRequest) obj;

    boolean result = true;
    result = result && (getTotal()
        == other.getTotal());
    result = result && (getLdl()
        == other.getLdl());
    result = result && (getHdl()
        == other.getHdl());
    result = result && (getTriglycerides()
        == other.getTriglycerides());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + getTotal();
    hash = (37 * hash) + LDL_FIELD_NUMBER;
    hash = (53 * hash) + getLdl();
    hash = (37 * hash) + HDL_FIELD_NUMBER;
    hash = (53 * hash) + getHdl();
    hash = (37 * hash) + TRIGLYCERIDES_FIELD_NUMBER;
    hash = (53 * hash) + getTriglycerides();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.jake.cholesterol.CholesterolRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.jake.cholesterol.CholesterolRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.jake.cholesterol.CholesterolRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.jake.cholesterol.CholesterolRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.jake.cholesterol.CholesterolRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.jake.cholesterol.CholesterolRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.jake.cholesterol.CholesterolRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.jake.cholesterol.CholesterolRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.jake.cholesterol.CholesterolRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.jake.cholesterol.CholesterolRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.jake.cholesterol.CholesterolRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.jake.cholesterol.CholesterolRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.jake.cholesterol.CholesterolRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpcheart.CholesterolRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpcheart.CholesterolRequest)
      grpc.jake.cholesterol.CholesterolRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.jake.cholesterol.CholesterolServiceImpl.internal_static_grpcheart_CholesterolRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.jake.cholesterol.CholesterolServiceImpl.internal_static_grpcheart_CholesterolRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.jake.cholesterol.CholesterolRequest.class, grpc.jake.cholesterol.CholesterolRequest.Builder.class);
    }

    // Construct using grpc.jake.cholesterol.CholesterolRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      total_ = 0;

      ldl_ = 0;

      hdl_ = 0;

      triglycerides_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.jake.cholesterol.CholesterolServiceImpl.internal_static_grpcheart_CholesterolRequest_descriptor;
    }

    @java.lang.Override
    public grpc.jake.cholesterol.CholesterolRequest getDefaultInstanceForType() {
      return grpc.jake.cholesterol.CholesterolRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.jake.cholesterol.CholesterolRequest build() {
      grpc.jake.cholesterol.CholesterolRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.jake.cholesterol.CholesterolRequest buildPartial() {
      grpc.jake.cholesterol.CholesterolRequest result = new grpc.jake.cholesterol.CholesterolRequest(this);
      result.total_ = total_;
      result.ldl_ = ldl_;
      result.hdl_ = hdl_;
      result.triglycerides_ = triglycerides_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.jake.cholesterol.CholesterolRequest) {
        return mergeFrom((grpc.jake.cholesterol.CholesterolRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.jake.cholesterol.CholesterolRequest other) {
      if (other == grpc.jake.cholesterol.CholesterolRequest.getDefaultInstance()) return this;
      if (other.getTotal() != 0) {
        setTotal(other.getTotal());
      }
      if (other.getLdl() != 0) {
        setLdl(other.getLdl());
      }
      if (other.getHdl() != 0) {
        setHdl(other.getHdl());
      }
      if (other.getTriglycerides() != 0) {
        setTriglycerides(other.getTriglycerides());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.jake.cholesterol.CholesterolRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.jake.cholesterol.CholesterolRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int total_ ;
    /**
     * <code>int32 total = 1;</code>
     */
    public int getTotal() {
      return total_;
    }
    /**
     * <code>int32 total = 1;</code>
     */
    public Builder setTotal(int value) {
      
      total_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total = 1;</code>
     */
    public Builder clearTotal() {
      
      total_ = 0;
      onChanged();
      return this;
    }

    private int ldl_ ;
    /**
     * <code>int32 ldl = 2;</code>
     */
    public int getLdl() {
      return ldl_;
    }
    /**
     * <code>int32 ldl = 2;</code>
     */
    public Builder setLdl(int value) {
      
      ldl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ldl = 2;</code>
     */
    public Builder clearLdl() {
      
      ldl_ = 0;
      onChanged();
      return this;
    }

    private int hdl_ ;
    /**
     * <code>int32 hdl = 3;</code>
     */
    public int getHdl() {
      return hdl_;
    }
    /**
     * <code>int32 hdl = 3;</code>
     */
    public Builder setHdl(int value) {
      
      hdl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 hdl = 3;</code>
     */
    public Builder clearHdl() {
      
      hdl_ = 0;
      onChanged();
      return this;
    }

    private int triglycerides_ ;
    /**
     * <code>int32 Triglycerides = 4;</code>
     */
    public int getTriglycerides() {
      return triglycerides_;
    }
    /**
     * <code>int32 Triglycerides = 4;</code>
     */
    public Builder setTriglycerides(int value) {
      
      triglycerides_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 Triglycerides = 4;</code>
     */
    public Builder clearTriglycerides() {
      
      triglycerides_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpcheart.CholesterolRequest)
  }

  // @@protoc_insertion_point(class_scope:grpcheart.CholesterolRequest)
  private static final grpc.jake.cholesterol.CholesterolRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.jake.cholesterol.CholesterolRequest();
  }

  public static grpc.jake.cholesterol.CholesterolRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CholesterolRequest>
      PARSER = new com.google.protobuf.AbstractParser<CholesterolRequest>() {
    @java.lang.Override
    public CholesterolRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CholesterolRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CholesterolRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CholesterolRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.jake.cholesterol.CholesterolRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

