// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bmi.proto

package grpc.jake.bmi;

public interface BmiAdviceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcheart.BmiAdvice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string link1 = 1;</code>
   */
  java.lang.String getLink1();
  /**
   * <code>string link1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getLink1Bytes();

  /**
   * <code>string link2 = 2;</code>
   */
  java.lang.String getLink2();
  /**
   * <code>string link2 = 2;</code>
   */
  com.google.protobuf.ByteString
      getLink2Bytes();
}
