// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bmi.proto

package grpc.jake.bmi;

/**
 * Protobuf type {@code grpcheart.BmiAdvice}
 */
public  final class BmiAdvice extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpcheart.BmiAdvice)
    BmiAdviceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BmiAdvice.newBuilder() to construct.
  private BmiAdvice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BmiAdvice() {
    link1_ = "";
    link2_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BmiAdvice(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            link1_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            link2_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.jake.bmi.BmiServiceImpl.internal_static_grpcheart_BmiAdvice_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.jake.bmi.BmiServiceImpl.internal_static_grpcheart_BmiAdvice_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.jake.bmi.BmiAdvice.class, grpc.jake.bmi.BmiAdvice.Builder.class);
  }

  public static final int LINK1_FIELD_NUMBER = 1;
  private volatile java.lang.Object link1_;
  /**
   * <code>string link1 = 1;</code>
   */
  public java.lang.String getLink1() {
    java.lang.Object ref = link1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      link1_ = s;
      return s;
    }
  }
  /**
   * <code>string link1 = 1;</code>
   */
  public com.google.protobuf.ByteString
      getLink1Bytes() {
    java.lang.Object ref = link1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      link1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LINK2_FIELD_NUMBER = 2;
  private volatile java.lang.Object link2_;
  /**
   * <code>string link2 = 2;</code>
   */
  public java.lang.String getLink2() {
    java.lang.Object ref = link2_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      link2_ = s;
      return s;
    }
  }
  /**
   * <code>string link2 = 2;</code>
   */
  public com.google.protobuf.ByteString
      getLink2Bytes() {
    java.lang.Object ref = link2_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      link2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getLink1Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, link1_);
    }
    if (!getLink2Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, link2_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getLink1Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, link1_);
    }
    if (!getLink2Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, link2_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.jake.bmi.BmiAdvice)) {
      return super.equals(obj);
    }
    grpc.jake.bmi.BmiAdvice other = (grpc.jake.bmi.BmiAdvice) obj;

    boolean result = true;
    result = result && getLink1()
        .equals(other.getLink1());
    result = result && getLink2()
        .equals(other.getLink2());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LINK1_FIELD_NUMBER;
    hash = (53 * hash) + getLink1().hashCode();
    hash = (37 * hash) + LINK2_FIELD_NUMBER;
    hash = (53 * hash) + getLink2().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.jake.bmi.BmiAdvice parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.jake.bmi.BmiAdvice parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.jake.bmi.BmiAdvice parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.jake.bmi.BmiAdvice parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.jake.bmi.BmiAdvice parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.jake.bmi.BmiAdvice parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.jake.bmi.BmiAdvice parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.jake.bmi.BmiAdvice parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.jake.bmi.BmiAdvice parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.jake.bmi.BmiAdvice parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.jake.bmi.BmiAdvice parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.jake.bmi.BmiAdvice parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.jake.bmi.BmiAdvice prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpcheart.BmiAdvice}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpcheart.BmiAdvice)
      grpc.jake.bmi.BmiAdviceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.jake.bmi.BmiServiceImpl.internal_static_grpcheart_BmiAdvice_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.jake.bmi.BmiServiceImpl.internal_static_grpcheart_BmiAdvice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.jake.bmi.BmiAdvice.class, grpc.jake.bmi.BmiAdvice.Builder.class);
    }

    // Construct using grpc.jake.bmi.BmiAdvice.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      link1_ = "";

      link2_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.jake.bmi.BmiServiceImpl.internal_static_grpcheart_BmiAdvice_descriptor;
    }

    @java.lang.Override
    public grpc.jake.bmi.BmiAdvice getDefaultInstanceForType() {
      return grpc.jake.bmi.BmiAdvice.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.jake.bmi.BmiAdvice build() {
      grpc.jake.bmi.BmiAdvice result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.jake.bmi.BmiAdvice buildPartial() {
      grpc.jake.bmi.BmiAdvice result = new grpc.jake.bmi.BmiAdvice(this);
      result.link1_ = link1_;
      result.link2_ = link2_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.jake.bmi.BmiAdvice) {
        return mergeFrom((grpc.jake.bmi.BmiAdvice)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.jake.bmi.BmiAdvice other) {
      if (other == grpc.jake.bmi.BmiAdvice.getDefaultInstance()) return this;
      if (!other.getLink1().isEmpty()) {
        link1_ = other.link1_;
        onChanged();
      }
      if (!other.getLink2().isEmpty()) {
        link2_ = other.link2_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.jake.bmi.BmiAdvice parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.jake.bmi.BmiAdvice) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object link1_ = "";
    /**
     * <code>string link1 = 1;</code>
     */
    public java.lang.String getLink1() {
      java.lang.Object ref = link1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        link1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string link1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLink1Bytes() {
      java.lang.Object ref = link1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        link1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string link1 = 1;</code>
     */
    public Builder setLink1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      link1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string link1 = 1;</code>
     */
    public Builder clearLink1() {
      
      link1_ = getDefaultInstance().getLink1();
      onChanged();
      return this;
    }
    /**
     * <code>string link1 = 1;</code>
     */
    public Builder setLink1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      link1_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object link2_ = "";
    /**
     * <code>string link2 = 2;</code>
     */
    public java.lang.String getLink2() {
      java.lang.Object ref = link2_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        link2_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string link2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLink2Bytes() {
      java.lang.Object ref = link2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        link2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string link2 = 2;</code>
     */
    public Builder setLink2(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      link2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string link2 = 2;</code>
     */
    public Builder clearLink2() {
      
      link2_ = getDefaultInstance().getLink2();
      onChanged();
      return this;
    }
    /**
     * <code>string link2 = 2;</code>
     */
    public Builder setLink2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      link2_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpcheart.BmiAdvice)
  }

  // @@protoc_insertion_point(class_scope:grpcheart.BmiAdvice)
  private static final grpc.jake.bmi.BmiAdvice DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.jake.bmi.BmiAdvice();
  }

  public static grpc.jake.bmi.BmiAdvice getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BmiAdvice>
      PARSER = new com.google.protobuf.AbstractParser<BmiAdvice>() {
    @java.lang.Override
    public BmiAdvice parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BmiAdvice(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BmiAdvice> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BmiAdvice> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.jake.bmi.BmiAdvice getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

