// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bmi.proto

package grpc.jake.bmi;

public interface BmiRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcheart.BmiRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float height = 1;</code>
   */
  float getHeight();

  /**
   * <code>float weight = 2;</code>
   */
  float getWeight();
}
