// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bmi.proto

package grpc.jake.bmi;

public interface BmiReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcheart.BmiReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double bmi = 1;</code>
   */
  double getBmi();

  /**
   * <code>string bmimessage = 2;</code>
   */
  java.lang.String getBmimessage();
  /**
   * <code>string bmimessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getBmimessageBytes();
}
