// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bmi.proto

package grpc.jake.bmi;

public interface BmiRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcheart.BmiRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double height = 1;</code>
   */
  double getHeight();

  /**
   * <code>double weight = 2;</code>
   */
  double getWeight();
}
