// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bmi.proto

package grpc.jake.bmi;

public final class BmiServiceImpl {
  private BmiServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcheart_BmiRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcheart_BmiRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcheart_BmiReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcheart_BmiReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcheart_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcheart_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcheart_BmiAdvice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcheart_BmiAdvice_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tbmi.proto\022\tgrpcheart\",\n\nBmiRequest\022\016\n\006" +
      "height\030\001 \001(\002\022\016\n\006weight\030\002 \001(\002\"+\n\010BmiReply" +
      "\022\013\n\003bmi\030\001 \001(\002\022\022\n\nbmimessage\030\002 \001(\t\"\007\n\005Emp" +
      "ty\")\n\tBmiAdvice\022\r\n\005link1\030\001 \001(\t\022\r\n\005link2\030" +
      "\002 \001(\t2x\n\003BMI\022<\n\016bmiCalculation\022\025.grpchea" +
      "rt.BmiRequest\032\023.grpcheart.BmiReply\0223\n\tbm" +
      "iAdvice\022\020.grpcheart.Empty\032\024.grpcheart.Bm" +
      "iAdviceB!\n\rgrpc.jake.bmiB\016BmiServiceImpl" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_grpcheart_BmiRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpcheart_BmiRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcheart_BmiRequest_descriptor,
        new java.lang.String[] { "Height", "Weight", });
    internal_static_grpcheart_BmiReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpcheart_BmiReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcheart_BmiReply_descriptor,
        new java.lang.String[] { "Bmi", "Bmimessage", });
    internal_static_grpcheart_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpcheart_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcheart_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_grpcheart_BmiAdvice_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_grpcheart_BmiAdvice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcheart_BmiAdvice_descriptor,
        new java.lang.String[] { "Link1", "Link2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
